### ISSUE TITLE
How to install in ableton 

### ISSUE THREAD

**Issue by Justjero** [ideoforms/AbletonOSC#1] opened 2021-05-04 19:37 UTC
Hi how do you install it in ableton 11 ? doesn't seem to show up

**Comment by bsom** [comment] 2021-06-08 23:57
> Hi how do you install it in ableton 11 ? doesn't seem to show up

I bet you're on a PC.  I'm having the same issue.  Works get on my Mac but I can't get it to show up on my PC.

**Comment by bsom** [comment] 2021-06-09 00:03
Change line 11 in manager.py from:
`tmp_dir = "/tmp"`
to:
`tmp_dir = "c:\Temp"`
then make sure that c:\Temp exists...

**Comment by bsom** [comment] 2021-06-09 00:05
Now c:\Temp\abletonosc.log gets spammed with:
`(2021-06-08 20:01:01,305) [INFO] AbletonOSC: Socket error: Traceback (most recent call last):
  File "C:\ProgramData\Ableton\Live 11 Suite\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 62, in process
    data, addr = self._socket.recvfrom(65536)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host`

**Comment by bsom** [comment] 2021-06-09 00:26
Now c:\Temp\abletonosc.log gets spammed with:
`(2021-06-08 20:26:04,961) [INFO] AbletonOSC: Socket error: Traceback (most recent call last):
  File "C:\ProgramData\Ableton\Live 11 Suite\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 62, in process
    data, addr = self._socket.recvfrom(65536)
BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed immediately`

**Comment by bsom** [comment] 2021-06-10 17:15
Some quick testing and I don't see these errors causing any actual failure, but just inflating the log file.  I disabled the log entry in the code, and it appears to be working correctly.  Reading about WinError 10035 online and lot of folks seems to think it is harmless and not worth trapping and logging.

**Comment by RickDDD** [comment] 2021-08-19 21:45
I can confirm that the original script does not show up on PC.
@bsom Thanks a lot for finding the culprit and the solution for the inflating log file!
@ideoforms Would be great to have this fixed or explained in the readme.
It should also be mentioned that the IPs have to be changed in osc_server.py for
non-local OSC apps.

**Comment by Michael-Z-Freeman** [comment] 2021-11-09 12:05
> Change line 11 in manager.py from: `tmp_dir = "/tmp"` to: `tmp_dir = "c:\Temp"` then make sure that c:\Temp exists...

This fix also works for me in Windows 10/Ableton 11. Turned logging off by commenting out "logger.addHandler(file_handler)". However I notice "file_handler.setLevel(logging.INFO)". Should that be changed to "CRIT", "WARN" to turn off all but the most relevant log items ?

**Comment by zengels** [comment] 2022-03-05 12:09
A chance to make it appear in ableton live 11.1, windows 10? i put the script in user\Documents\Ableton\User Library\Remote Scripts , no luck Then in C:\ProgramData\Ableton\Live 11 Suite\Resources\MIDI Remote Scripts , no luck to .
I also : "Change line 11 in manager.py from:
tmp_dir = "/tmp"
to:
tmp_dir = "c:\Temp"
then make sure that c:\Temp exists... "
Nothing...

**Comment by bsom** [comment] 2022-04-04 20:19
I had this working in Live 11.0 then I made the mistake of updating to Live 11.1.  It broke.  So I downgraded back to Live 11.0 and now it still doesn't work.  What the hell?!? :-)

**Comment by bsom** [comment] 2022-04-05 15:06
Even more interesting: It works just fine on my Mac with Live 11.1.1 but no go on my Windows 10 machine with same version of Live.  Trying to figure out where it falls apart...

**Comment by bsom** [comment] 2022-04-05 15:54
OK, I figured it out.

In manager.py, the commands to construct the log path seem to have changed what they return.  Their return value was adding "c:\\windows\\system32\\" to the returned string.

As a simple workaround, I simply commented out the lines:
tmp_dir = "/tmp"
log_path = os.path.join(tmp_dir, "abletonosc.log")

And replaced them with a hard-coded path:
log_path="c:\\temp\\abletonosc.log"

I'm sure there is a more elegant way to solve this but this was done just to investigate the issue.

**Comment by ideoforms** [comment] 2022-11-16 22:03
I've now resolved this more elegantly by having the script create and log to a folder called `logs` relative to the AbletonOSC top-level directory, which should resolve these Windows path issues. Thanks @RickDDD for the idea and help with testing.

**Closed by ideoforms** 2022-11-16 22:03 UTC
